version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: sadok
      POSTGRES_PASSWORD: azerty
      POSTGRES_DB: nest
    volumes:
      - .dbata:/var/lib/postgres
    networks:
      - net

  redis:
    image: redis:latest
    ports:
    - 6379:6379
    networks:
    - net

  mailhog:
    image: mailhog/mailhog
    ports:
    - 1025:1025
    - 8025:8025
    networks:
      - net

  backend:
    container_name: backend
    image: raniamidoaui/backend
    
    build:
      context: ./Ambassador_App_NestJs-main/Ambassador_App_NestJs-main
      dockerfile: Dockerfile.prod
    volumes:
      - ./Ambassador_App_NestJs-main/Ambassador_App_NestJs-main/src:/backend/src
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: sadok
      DB_PASSWORD: azerty
      DB_DATABASE: nest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MAILHOG_HOST: mailhog
      MAILHOG_PORT: 1025
      MAILHOG_EMAIL: no-reply@example.com
    depends_on:
      - db
    networks:
      - net
  
  nextfront:
    image: raniamidaoui/nextfront
    build:
      context: ./Ambassador_App_Frontend-main/Ambassador_App_Frontend-main/next-checkout
      dockerfile: Dockerfile
      target: runner
    volumes:
      - ./Ambassador_App_Frontend-main/Ambassador_App_Frontend-main/next-checkout/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - net
    environment:
      NODE_ENV: development

  adminfront:
    container_name: admin-app
    image: raniamidaoui/admin-app
    build:
      context: ./Ambassador_App_Frontend-main/Ambassador_App_Frontend-main/react-admin
      dockerfile: Dockerfile
    volumes:
      - ./Ambassador_App_Frontend-main/Ambassador_App_Frontend-main/react-admin/src:/adminfront/src
    ports:
      - 5200:5200  
    depends_on:
      - backend
    networks:
      - net

  ambassadorfront:
    container_name: ambass-app
    image: raniamidaoui/ambass-app

    build:
      context: ./Ambassador_App_Frontend-main/Ambassador_App_Frontend-main/react-ambassador
      dockerfile: Dockerfile
    volumes:
      - ./Ambassador_App_Frontend-main/Ambassador_App_Frontend-main/react-ambassador/src:/ambassfront/src
    ports:
      - 4000:4000  
    depends_on:
      - backend
    networks:
      - net

networks:
    net: 
